### ISSUE TITLE
Reporte hilos

### ISSUE THREAD

**Issue by ArturoAngonJose** [SistemasTecTlaxiaco/practica-de-hilos-ArturoAngonJose#2]
[Reporte-Hilos.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-hilos-ArturoAngonJose/files/6505606/Reporte-Hilos.pdf)

**Comment by Band-hi** [comment]
Calificación 18.4/20

Calificó: Gandhi Salazar Cruz

**Comment by josealfredo79** [comment]
Bien hecho y revisado
